// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace MVCApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250507021212_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Acceptance", b =>
                {
                    b.Property<int>("Acceptance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Acceptance_ID"));

                    b.Property<string>("Acceptance_Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Accepted_Total")
                        .HasColumnType("int");

                    b.Property<DateTime>("Finish_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Invoice_ID")
                        .HasColumnType("int");

                    b.Property<int>("Invoice_Total")
                        .HasColumnType("int");

                    b.Property<int>("Multi_User")
                        .HasColumnType("int");

                    b.Property<string>("Purchase_Order_ID")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("Start_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Acceptance_ID");

                    b.ToTable("Acceptance");
                });

            modelBuilder.Entity("Entities.Models.ActiveAcceptanceControl", b =>
                {
                    b.Property<int>("Active_Acceptance_Control_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Active_Acceptance_Control_ID"));

                    b.Property<int>("Acceptance_ID")
                        .HasColumnType("int");

                    b.Property<int>("Accepted_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Invoice_Quantity")
                        .HasColumnType("int");

                    b.HasKey("Active_Acceptance_Control_ID");

                    b.ToTable("ActiveAcceptanceControls");
                });

            modelBuilder.Entity("Entities.Models.ActiveInvoiceList", b =>
                {
                    b.Property<int>("Active_Invoice_List_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Active_Invoice_List_ID"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Invoice_ID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Active_Invoice_List_ID");

                    b.ToTable("Active_Invoice_List");
                });

            modelBuilder.Entity("Entities.Models.ActivePurchaseOrderList", b =>
                {
                    b.Property<int>("Active_Purchase_Order_List_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Active_Purchase_Order_List_ID"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Invoiced_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Purchase_Order_ID")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Active_Purchase_Order_List_ID");

                    b.ToTable("Active_Purchase_Order_List");
                });

            modelBuilder.Entity("Entities.Models.Bid", b =>
                {
                    b.Property<int>("BidID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<int>("TenderID")
                        .HasColumnType("int");

                    b.HasKey("BidID");

                    b.HasIndex("SupplierID");

                    b.HasIndex("TenderID");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Entities.Models.Invoice", b =>
                {
                    b.Property<int>("Invoice_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Invoice_ID"));

                    b.Property<DateTime>("Delivery_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gate_Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("Invoice_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Invoice_Number")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Invoice_Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Invoice_Total")
                        .HasColumnType("int");

                    b.Property<string>("Purchase_Order_ID")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Warehouse_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Invoice_ID");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Property<int>("Location_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Location_ID"));

                    b.Property<int>("Block_Explanation_ID")
                        .HasColumnType("int");

                    b.Property<float>("Capacity")
                        .HasColumnType("real");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location_Address")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Location_Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Location_Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<float>("Used_Capacity")
                        .HasColumnType("real");

                    b.Property<string>("Warehouse_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Location_ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Entities.Models.PurchaseOrder", b =>
                {
                    b.Property<string>("Purchase_Order_ID")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("Expected_Delivery_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Invoice_Total")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purchase_Order_Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Supplier_Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("Total_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Purchase_Order_ID");

                    b.ToTable("Purchase_Order");
                });

            modelBuilder.Entity("Entities.Models.RawMaterialData", b =>
                {
                    b.Property<string>("Company_Barcode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Fabric_Composition")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Old_Barcode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Company_Barcode");

                    b.ToTable("Raw_Material_Data");
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Property<string>("Role_Name")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<bool>("Acceptance_Hand")
                        .HasColumnType("bit");

                    b.Property<bool>("Acceptance_PC")
                        .HasColumnType("bit");

                    b.Property<bool>("Analitics")
                        .HasColumnType("bit");

                    b.Property<bool>("Buyer")
                        .HasColumnType("bit");

                    b.Property<bool>("Carriage_Hand")
                        .HasColumnType("bit");

                    b.Property<bool>("Carriage_PC")
                        .HasColumnType("bit");

                    b.Property<bool>("Parameters")
                        .HasColumnType("bit");

                    b.Property<bool>("Picking_Hand")
                        .HasColumnType("bit");

                    b.Property<bool>("Picking_PC")
                        .HasColumnType("bit");

                    b.Property<bool>("PreAcceptance_Hand")
                        .HasColumnType("bit");

                    b.Property<bool>("PreAcceptance_PC")
                        .HasColumnType("bit");

                    b.Property<bool>("Reports")
                        .HasColumnType("bit");

                    b.Property<bool>("Shipment_Bag_Hand")
                        .HasColumnType("bit");

                    b.Property<bool>("Shipment_Bag_PC")
                        .HasColumnType("bit");

                    b.HasKey("Role_Name");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Entities.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Contact_Person")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("E_Mail")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Supplier_Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Tax_ID")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Entities.Models.Tender", b =>
                {
                    b.Property<int>("TenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenderID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TenderID");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("User_Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("E_Mail")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("User_Name");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Models.Bid", b =>
                {
                    b.HasOne("Entities.Models.Supplier", "Supplier")
                        .WithMany("Bids")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tender", "Tender")
                        .WithMany("Bids")
                        .HasForeignKey("TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("Entities.Models.Supplier", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Entities.Models.Tender", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
